name: ggspot
favicon: null
layout_spectrum: 0.28386639477685094
typography_spectrum: 0.18323231651447713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.19596979534253478
  lightness: 0.9858335100580007
  saturation: 0.027279231930151582
  rhythmicContrast: 0.533110436052084
purpose: []
